<a href="https://colab.research.google.com/github/gabrielbklopes/AICodes/blob/main/desafioModulo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd  #bibioteca responsável para o tratamento e limpeza dos dados
import numpy as np #biblioteca utilizada para o tratamento eficiente de dados numéricos
import datetime  #biblioteca utilizada para trabalhar com datas
from matplotlib import pyplot as plt  #plotar os gráficos
import seaborn as sns #plot de gráficos
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from google.colab import files
uploded = files.upload()

Saving winequality-red.csv to winequality-red.csv


In [ ]:
df_wine = pd.read_csv('winequality-red.csv', sep=';')

In [ ]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
df_wine.shape

(1599, 12)

In [ ]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
df_wine.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [ ]:
df_wine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
df_wine.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [ ]:
df_wine['fixed acidity'].corr(df_wine['pH'])

-0.6829781945685316

In [ ]:
df_wine.corr()

fixed acidity  volatile acidity  ...   alcohol   quality
fixed acidity              1.000000         -0.256131  ... -0.061668  0.124052
volatile acidity          -0.256131          1.000000  ... -0.202288 -0.390558
citric acid                0.671703         -0.552496  ...  0.109903  0.226373
residual sugar             0.114777          0.001918  ...  0.042075  0.013732
chlorides                  0.093705          0.061298  ... -0.221141 -0.128907
free sulfur dioxide       -0.153794         -0.010504  ... -0.069408 -0.050656
total sulfur dioxide      -0.113181          0.076470  ... -0.205654 -0.185100
density                    0.668047          0.022026  ... -0.496180 -0.174919
pH                        -0.682978          0.234937  ...  0.205633 -0.057731
sulphates                  0.183006         -0.260987  ...  0.093595  0.251397
alcohol                   -0.061668         -0.202288  ...  1.000000  0.476166
quality                    0.124052         -0.390558  ...  0.476166  1.000000

[12 rows x 12 columns]

In [ ]:
df_wine['quality'].corr(df_wine['alcohol'])

0.4761663240011358

In [ ]:
df_wine['quality']

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [ ]:
df_wine.pivot_table(index=['quality'], aggfunc='size')

quality
3     10
4     53
5    681
6    638
7    199
8     18
dtype: int64

In [ ]:
scaler = MinMaxScaler()

In [ ]:
new_df_wine = df_wine

In [ ]:
new_df_wine = scaler.fit_transform(new_df_wine)

In [ ]:
new_df_wine = pd.DataFrame(new_df_wine)

In [ ]:
new_df_wine

0         1     2         3   ...        8         9         10   11
0     0.247788  0.397260  0.00  0.068493  ...  0.606299  0.137725  0.153846  0.4
1     0.283186  0.520548  0.00  0.116438  ...  0.362205  0.209581  0.215385  0.4
2     0.283186  0.438356  0.04  0.095890  ...  0.409449  0.191617  0.215385  0.4
3     0.584071  0.109589  0.56  0.068493  ...  0.330709  0.149701  0.215385  0.6
4     0.247788  0.397260  0.00  0.068493  ...  0.606299  0.137725  0.153846  0.4
...        ...       ...   ...       ...  ...       ...       ...       ...  ...
1594  0.141593  0.328767  0.08  0.075342  ...  0.559055  0.149701  0.323077  0.4
1595  0.115044  0.294521  0.10  0.089041  ...  0.614173  0.257485  0.430769  0.6
1596  0.150442  0.267123  0.13  0.095890  ...  0.535433  0.251497  0.400000  0.6
1597  0.115044  0.359589  0.12  0.075342  ...  0.653543  0.227545  0.276923  0.4
1598  0.123894  0.130137  0.47  0.184932  ...  0.511811  0.197605  0.400000  0.6

[1599 rows x 12 columns]

In [ ]:
new_df_wine.describe()

0            1   ...           10           11
count  1599.000000  1599.000000  ...  1599.000000  1599.000000
mean      0.329171     0.279329  ...     0.311228     0.527205
std       0.154079     0.122644  ...     0.163949     0.161514
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.221239     0.184932  ...     0.169231     0.400000
50%       0.292035     0.273973  ...     0.276923     0.600000
75%       0.407080     0.356164  ...     0.415385     0.600000
max       1.000000     1.000000  ...     1.000000     1.000000

[8 rows x 12 columns]

In [ ]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
entradas_normalizadas = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
saida = ['quality']
saida

['quality']

In [ ]:
x = new_df_wine[entradas_normalizadas]
y = df_wine[saida]
x

0         1     2   ...        8         9         10
0     0.247788  0.397260  0.00  ...  0.606299  0.137725  0.153846
1     0.283186  0.520548  0.00  ...  0.362205  0.209581  0.215385
2     0.283186  0.438356  0.04  ...  0.409449  0.191617  0.215385
3     0.584071  0.109589  0.56  ...  0.330709  0.149701  0.215385
4     0.247788  0.397260  0.00  ...  0.606299  0.137725  0.153846
...        ...       ...   ...  ...       ...       ...       ...
1594  0.141593  0.328767  0.08  ...  0.559055  0.149701  0.323077
1595  0.115044  0.294521  0.10  ...  0.614173  0.257485  0.430769
1596  0.150442  0.267123  0.13  ...  0.535433  0.251497  0.400000
1597  0.115044  0.359589  0.12  ...  0.653543  0.227545  0.276923
1598  0.123894  0.130137  0.47  ...  0.511811  0.197605  0.400000

[1599 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1) 

In [ ]:
clf_KNN = KNeighborsClassifier(n_neighbors=5)

In [ ]:
clf_KNN.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_predict = clf_KNN.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
acuracia = accuracy_score(y_test, y_predict)
print('Acurácia do KNeighbors: ',acuracia)

Acurácia do KNeighbors:  0.5645833333333333


In [ ]:
clf_tree = DecisionTreeClassifier()
clf_tree.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_predict_tree = clf_tree.predict(x_test)
acuraria_tree = accuracy_score(y_test, y_predict_tree)
print('Acuraria da arvore de decisãa: ', acuraria_tree)

Acuraria da arvore de decisãa:  0.6125


In [ ]:
entradas = ['fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides',	'free sulfur dioxide',	'total sulfur dioxide',	'density',	'pH',	'sulphates',	'alcohol']

In [ ]:
x_new = df_wine[entradas]
x_new

fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0               7.4             0.700         0.00  ...  3.51       0.56      9.4
1               7.8             0.880         0.00  ...  3.20       0.68      9.8
2               7.8             0.760         0.04  ...  3.26       0.65      9.8
3              11.2             0.280         0.56  ...  3.16       0.58      9.8
4               7.4             0.700         0.00  ...  3.51       0.56      9.4
...             ...               ...          ...  ...   ...        ...      ...
1594            6.2             0.600         0.08  ...  3.45       0.58     10.5
1595            5.9             0.550         0.10  ...  3.52       0.76     11.2
1596            6.3             0.510         0.13  ...  3.42       0.75     11.0
1597            5.9             0.645         0.12  ...  3.57       0.71     10.2
1598            6.0             0.310         0.47  ...  3.39       0.66     11.0

[1599 rows x 11 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size=0.3, random_state=1) 

In [ ]:
clf_tree_new = DecisionTreeClassifier()
clf_tree_new.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_predict_tree_new = clf_tree_new.predict(x_test)

In [ ]:
acuracia_tree_new = accuracy_score(y_test, y_predict_tree_new)
print('Acurácia da àrvore de Decisão: ',acuracia_tree_new)

Acurácia da àrvore de Decisão:  0.9208333333333333


In [ ]:
clf_random = RandomForestClassifier(max_depth=10, random_state=1)
clf_random.fit(x_train, y_train)
y_predict_random = clf_random.predict(x_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [ ]:
acuracia_random = accuracy_score(y_test, y_predict_random)
print('Acurácia da àrvore de Decisão: ',acuracia_random)

Acurácia da àrvore de Decisão:  0.9520833333333333


In [ ]:
clf_svm = SVC(gamma='auto',kernel='rbf')
clf_svm.fit(x_train, y_train)
y_predict_svm = clf_svm.predict(x_test)
acuracia_svm = accuracy_score(y_test, y_predict_svm)
print('Acuracia SVM: ', acuracia_svm)

Acuracia SVM:  0.9520833333333333


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input, Dropout
from tensorflow.keras.optimizers import SGD

In [ ]:
camada_entrada = Input(shape=(10,), dtype='float32')

In [ ]:
clf_mlp = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(5,5), random_state=1)

In [ ]:
clf_mlp.fit(x_train, y_train)
y_predict_mlp = clf_mlp.predict(x_test)
acuracia_mlp = accuracy_score(y_test, y_predict_mlp)
print('Acuracia MLP: ', acuracia_mlp)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Acuracia MLP:  0.9520833333333333


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix (y_test, y_predict))
print('\n')
print(confusion_matrix(y_test, y_predict_tree))
print('\n')
print(confusion_matrix(y_test, y_predict_mlp))
print('\n')
print(confusion_matrix(y_test, y_predict_tree))
print('\n')
print(confusion_matrix(y_test, y_predict_random))
print('\n')
print(confusion_matrix(y_test, y_predict_svm))

[[  0   0   1   1  15   5   1]
 [  0   0   0   2 228 180  47]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]]


[[  0   0   2   2  11   5   3   0]
 [  0   0   2   8 210 168  65   4]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]


[[  0  23]
 [  0 457]]


[[  0   0   2   2  11   5   3   0]
 [  0   0   2   8 210 168  65   4]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]


[[  0  23]
 [  0 457]]


[[  0  23]
 [  0 457]]


In [ ]:
df_wine.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
df_wine2 = df_wine

In [ ]:
df_wine2.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
df_wine2.quality[df_wine2.quality < 5] = 0
df_wine2.quality[df_wine2.quality >= 5] = 1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
df_wine2.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        1
1            7.8              0.88         0.00  ...       0.68      9.8        1
2            7.8              0.76         0.04  ...       0.65      9.8        1
3           11.2              0.28         0.56  ...       0.58      9.8        1
4            7.4              0.70         0.00  ...       0.56      9.4        1

[5 rows x 12 columns]

In [ ]:
saida = ['quality']
entradas = ['fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides',	'free sulfur dioxide',	'total sulfur dioxide',	'density',	'pH',	'sulphates',	'alcohol']
x = df_wine2[entradas]
y = df_wine2[saida]
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size=0.3, random_state=1) 
clf_mlp = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(5,5), random_state=1)
clf_mlp.fit(x_train, y_train)
y_predict_mlp = clf_mlp.predict(x_test)
acuracia_mlp = accuracy_score(y_test, y_predict_mlp)
print('Acuracia MLP: ', acuracia_mlp)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Acuracia MLP:  0.9520833333333333


In [ ]:
saida = ['quality']
entradas = ['fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides',	'free sulfur dioxide',	'total sulfur dioxide',	'density',	'pH',	'sulphates',	'alcohol']
x = df_wine2[entradas]
y = df_wine2[saida]
y

quality
0           1
1           1
2           1
3           1
4           1
...       ...
1594        1
1595        1
1596        1
1597        1
1598        1

[1599 rows x 1 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size=0.3, random_state=1)

In [ ]:
clf_random = RandomForestClassifier(max_depth=10, random_state=1)
clf_random.fit(x_train, y_train)
y_predict_random = clf_random.predict(x_test)
acuracia_random = accuracy_score(y_test, y_predict_random)
print('Acurácia da floresta randomica: ',acuracia_random)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


Acurácia da floresta randomica:  0.9520833333333333
